### ISSUE TITLE
Unable to resize SAML Trace Window

### ISSUE THREAD

**Issue by usethedata** [UNINETT/SAML-tracer#17]
Sorry if this is a stupid, but I've looked to find the answer and I'm getting nowhere. The gist is that on a Mac (10.10), I'm unable to resize the SAML Tracer window to make reading the SAML traces easer.  I have a memory that I was able to do this before, so maybe there's a Mac update or Firefox update that's affected this.

**Comment by olavmrk** [comment]
It is possible to resize the window on other platforms, and it was supposed to be possible to do so on a Mac as well, but for some reason it doesn't work. @jaimeperez has mentioned the same problem to me, so it is certainly not only your installation. 

Unfortunately, as I don't have a Mac, I haven't been able to debug this problem. If someone with a Mac wants to take a look at it, a good place to start is probably the [window declaration](https://github.com/UNINETT/SAML-tracer/blob/master/chrome/samltrace/content/TraceWindow.xul) and the [script that shows the window](https://github.com/UNINETT/SAML-tracer/blob/f74c8b6b15f6164c80d39b3d159dc38dabc830cf/bootstrap.js#L23).

Patches welcome!

**Comment by jaimeperez** [comment]
I can confirm the issue in the latest versions of both Firefox and Firefox for developers. It's been like that for a while, and I think the issue appeared again (after being fixed) with the last version of SAML tracer. Can't confirm this last point, though.

**Comment by thijskh** [comment]
Is #16 the solution to this or not? I cannot verify since on my platform, resizing works just fine.

**Comment by jaimeperez** [comment]
I've just verified that it works with both *Firefox* and *FirefoxDeveloperEdition*, so I'm merging #16.
