### ISSUE TITLE
FireFox requires add-ons to be signed

### ISSUE THREAD

**Issue by dominique-p** [UNINETT/SAML-tracer#21]
Hello,
the latest Firefox browser want their add-ons to be signed. This was introduced with Firefox 45 and will be obligatory from Firefox 48:

> If a signed version is not available, contact the add-on developer or vendor to see if they can offer an updated and signed version of that add-on. You can also ask them to get their add-on signed.

cf. Add-on signing in Firefox
https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Add-on-signing-in-Firefox/ta-p/30262#w_what-can-i-do-if-firefox-disables-an-installed-add-on

This extension is so useful that I am dreading the day it could be disabled because of a signing policy!
I hope a signed version will be available before Firefox 48 is released.

Thanks in advance!

Dominique point Petitpierre at unige point ch

**Comment by inetquestion** [comment]
Any updates on this?  Has anyone cloned this who is currently maintaining under a different name?

**Comment by thijskh** [comment]
Why is this necessary? You can get this extension from Mozilla Add-ons and it will be properly signed. If you install it from source for development you need to disable signing, this is documented. But that cannot be signed if you want to change the source. What value would there be in providing a signed add-on separate to the one in Mozilla Add-ons?

**Comment by thijskh** [comment]
No longer relevant for 1.0
