### ISSUE TITLE
No longer support in the Firefox v57 (Developer edition)

### ISSUE THREAD

**Issue by joseph-so** [UNINETT/SAML-tracer#22]
This plugin is marked as a legacy plugin in v57 and disabled.

**Comment by thijskh** [comment]
Which version of the extension are you using?

**Comment by joseph-so** [comment]
0.4.0, the latest version in the Firefox Add-ons store. I believe it is related to this https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct.

I still can use it in the Firefox (non-developer edition) v 55.0.3, but the addon page mentioned it is legacy

**Comment by fkooman** [comment]
See also https://arewewebextensionsyet.com/

**Comment by fkooman** [comment]
From November (Firefox 57 release date) it will stop working for everyone. You can still use ESR for a while I guess.

**Comment by khlr** [comment]
@thijskh Are there any plans on migrating samltracer to a WebExtension?

**Comment by thijskh** [comment]
I'm not the maintainer of SAML-Tracer but would also surely be interested in it to keep on working.

**Comment by jaimeperez** [comment]
I haven't had time to look into this, and unfortunately I don't think I'll have in the near future. In any case, I really think someone with more knowledge (or any, in this case 😅 ) of SAMLtracer than me should take care of this. Don't know if @olavmrk could find some time at some point for it.

**Comment by khlr** [comment]
Did you consider marking this (and other issues) with the #hacktoberfest label? ;)

**Comment by jaimeperez** [comment]
>Did you consider marking this (and other issues) with the #hacktoberfest label? ;)

I didn't even know about it, but thanks a lot for the tip! 😄

**Comment by DanielMalmgren** [comment]
...and today FF 57 was rolled out. This was an important utility for me, quite handicapped now. Any hope on it getting fixed?

**Comment by thijskh** [comment]
@DanielMalmgren  Yes, see #23. Your help is welcome there.

**Comment by thijskh** [comment]
Fixed in 1.0!

**Comment by martinhaase** [comment]
It does work on my Windows box, but not on Linux... 57.0 here, current Fedora, the SAML tracer window opens but is blank, with a moz-extension://<some uuid> title. Any help?

**Comment by thijskh** [comment]
Right-click the window and the contents will appear. This seems to be a FF-bug

**Comment by martinhaase** [comment]
great, thanks, that worked! :)

**Comment by thijskh** [comment]
Other extensions (e.g. "Kee" formerly known as "KeeFox") show the same behaviour so it's indeed likely a FF bug.

**Comment by thijskh** [comment]
It now seems to work correctly in FF 63.

**Comment by khlr** [comment]
Cool, works for, too!
Finally! :-)
