### ISSUE TITLE
Only select relevant info upon ctrl+A

### ISSUE THREAD

**Issue by DanielMalmgren** [UNINETT/SAML-tracer#28]
A minor annoyance in 1.0: When i Click in the lower half of the window (ie where the HTTP/Parameters/SAML is displayed) and press ctrl+A the logical thing would be if only the stuff in that part of the window is selected. I often use this to copy the SAML ticket somewhere else and I'm almost sure it worked that way in 0.4. If I do that in 1.0 it also selects the upper half, ie the list of HTTP calls.

**Comment by khlr** [comment]
Hello Daniel!

You're right, that behaviour definitely changed from 0.4.0 to 1.0.0!

Let me explain why:
Formerly, the XUL-based UI consisted of "real" controls. The control that held the details confined the impact of the ctrl+a to its own contents. 
Now the whole UI is made of HTML. Hence it acts like an arbitrary website: If you press ctrl+a somewhere in this GitHub issue, the entire document will be selected.

I'll see how to best workaround this.

**Comment by DanielMalmgren** [comment]
Maybe simply a "select all" button? Or even better, a "copy ticket" that puts the SAML contents in the copy buffer?

**Comment by khlr** [comment]
I think, I'd favour to just capture the keydown-event an handle the ctrl+a. 
We could achieve the desired behaviour this way, and avoid having a distinct button for this case.

I'll see what I can do until next weekend.

**Comment by jaimeperez** [comment]
This is solved in 1.1.
