### ISSUE TITLE
Name of the extension

### ISSUE THREAD

**Issue by khlr** [UNINETT/SAML-tracer#39]
This may not be a big deal, but anyways ;-)

The other day I stumbled about the extension's name. It's different in various locations:

* Here in the repo at Github the extension's name is `SAML-tracer` (hypen + lower t)
* In the code (esp. in the readme.md) it's `SAML Tracer` (whitespace + upper t)
* At the Firefox Addons Page it's `SAML tracer` (whitespace + lower t)

I'd suggest `SAML-tracer`. This term is already present in various places and wouldn't break existing hyperlinks. At least in the URLs I saw up to now, the hyphen was already present.

What do you think? Would it be a good idea to harmonize the name (e.g. for a better recognition value and unambiguity)? Or is this needless fuss?

**Comment by jaimeperez** [comment]
Hi @khlr!

I don't think this is a needless fuss in any way. Actually, I pretty much agree with you, as I find myself with the same trouble all over again. I don't have any special preferences, so whatever is easier to change /breaks less stuff works fine for me 😉

**Comment by khlr** [comment]
Ok, then I'll do the necessary code changes in the near future. It's just a small thing 😉

Is there a way to change the name at the Addons Page from `SAML tracer` to `SAML-tracer`, @jaimeperez?
I mean that's not absolutely necessary, but would be the icing on the cake 😁

![image](https://user-images.githubusercontent.com/17160647/36689718-84edb732-1b30-11e8-88ba-b82109947cde.png)

Anyways, the URL will stay the same: https://addons.mozilla.org/firefox/addon/saml-tracer/

**Comment by jaimeperez** [comment]
Great, thanks!

I’m not entirely sure it’s possible, but i’ll check :-)

--
Jaime

On 26 Feb 2018, at 20:07, Jan Köhler <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, then I'll do the necessary code changes in the near future. It's just a small thing 😉

Is there a way to change the name at the Addons Page from SAML tracer to SAML-tracer, @jaimeperez<https://github.com/jaimeperez>?
I mean that's not absolutely necessary, but would be the icing on the cake 😁

[image]<https://user-images.githubusercontent.com/17160647/36689718-84edb732-1b30-11e8-88ba-b82109947cde.png>

Anyways, the URL will stay the same: https://addons.mozilla.org/firefox/addon/saml-tracer/

**Comment by jaimeperez** [comment]
... aaand there we have the [icing](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) 🍾
