### ISSUE TITLE
Add up-to-date screenshots

### ISSUE THREAD

**Issue by khlr** [UNINETT/SAML-tracer#41]
Another probably small issue 😉

Now that the extension's name has been updated, it'd be nice if there'd be at least one (or more) up-to-date screenshots of SAML-tracer at the Firefox Addons Page. Currently there's a really old screenshot. If I were new to SAML-tracer and I'd start it for the first time, I'd be surprised that the actual extension looked significantly other than shown on the screenshot.

Unfortunately I've no access to IDPs/SPs which I could use for demonstration screenshots. From the old screenshot I noticed that there's a test-SP at Feide (https://sp-test.feide.no/), but I've got no access to any of the IDPs. Anyways, I attached one screenshot with a few requests:

![image](https://user-images.githubusercontent.com/17160647/36748888-80130bda-1bf9-11e8-8de5-e87d1e087ca9.png)

@jaimeperez or anybody else who's got no problem in disclosing somethin on a screenshot 😁 Do you think you could create some more interesting screenshots? E.g. one showing a SAMLresponse?

(Please note: I used the current master for the screenshot since there's already the updated title of the trace window in place)

**Comment by tvdijen** [comment]
![afbeelding](https://user-images.githubusercontent.com/841045/36755876-cb871b06-1c0d-11e8-9f93-1639c8eea57c.png)
The whole reponse is too big, but does this help?

**Comment by khlr** [comment]
Thanks @tvdijen! I think that one serves as a really good example since it shows a lot of content 👍

**Comment by tvdijen** [comment]
By the wat, you should still have access on my IdP @khlr..

**Comment by jaimeperez** [comment]
Updated! I've also taken the chance to change the icon of the extension to match the one displayed in the toolbar.

Thanks a lot guys!
