### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by khlr** [Uninett/SAML-tracer#42]
I'm still not too happy with the SAML logo (<img src="https://github.com/UNINETT/SAML-tracer/raw/master/src/resources/images/saml.png" alt="SAML Logo" width="16" />) in the browser toolbar. And I don't think it serves as a too good logo at the Firefox Addons page either ;-)

So, I assembled all my creative skills ... ![ugly](http://www.smilietown.de/smilies/ugly/ulgy_01.gif) ... and made some drafts for a new logo of SAML-tracer. 
Interpretation help: It should represent the stylized letter S. And the whole scene should depict some kind of trace  ;-)
Do you like one of them?

## draft 4a:
![image](https://user-images.githubusercontent.com/17160647/36935314-b2b29718-1ef6-11e8-8ab9-2b220769d656.png)

## draft4b:
![image](https://user-images.githubusercontent.com/17160647/36935289-6ffcb16a-1ef6-11e8-9a9c-998c6cc9a767.png)

## draft 4c:
![image](https://user-images.githubusercontent.com/17160647/36935265-02633d22-1ef6-11e8-83b4-bee4aec26071.png)

## draft 4d:
![image](https://user-images.githubusercontent.com/17160647/36935235-a4457d4a-1ef5-11e8-9613-fcadca02055c.png)

## draft 5a:
![image](https://user-images.githubusercontent.com/17160647/36936667-6c8bf89e-1f08-11e8-93c1-2d0c37a1ff74.png)

## draft 5b:
![image](https://user-images.githubusercontent.com/17160647/36936934-fda5611e-1f0b-11e8-8b07-ed02d159d995.png)

## draft 5c:
![image](https://user-images.githubusercontent.com/17160647/36937113-b7ff17ce-1f0e-11e8-8a4e-ebe342cc80b8.png)

## draft 6a:
![image](https://user-images.githubusercontent.com/17160647/36945579-f0f110ee-1fb0-11e8-972e-68eddc7f5584.png)

**Comment by jaimeperez** [comment]
Oh well, I can tell you then that your creative skills are awesome compared to mine 😝

If I have to choose, I think I'd stick with **4d**, as I believe it would be easier to see. I like all of them though, and it's probably much better than my initial idea to include a loupe icon 😆

**Comment by khlr** [comment]
I had something like that in mind, too (see draft 5a above).
But I think most times a loupe icon is utilized for a *search* functionality rather than for an *inspect* functionality.

**Comment by jaimeperez** [comment]
That's true...

What about putting the loupe between XML angles? Something like: `< 🔍>`. Maybe it's too wide for a squared logo, but just an idea...

**Comment by khlr** [comment]
🤔

**Comment by thijskh** [comment]
I actually quite like 5c...

**Comment by khlr** [comment]
I added another one: 6a
But I'm afraid one doesn't recognize the key in the 16px icon...

**Comment by tvdijen** [comment]
Why not best of both; something like this:  https://goo.gl/images/bSh9Mc

**Comment by khlr** [comment]
I _really_ (!) like that icon, @tvdijen! I played a little bit around with that model, but unfortunately I don't manage to make our drafts to look similar without plainly plagiarizing it. And I don't feel comfortable with somewhat copying someone other's work. That's the least thing I wanna do. I hope you understand my point 🙂

I also tried to make another category-4-draft with dots and lines. Bit in the end this looked more like a bicycle chain than like a trace... 😁

Are there any other ideas? Or should we stick with the current drafts? 
Or would it be better if we did not take any of them? I think the most important thing is the 16px representation, because that's the icon which the user sees in the browser tool bar and which should ideally be easily associated with SAML-tracer. And personally I think, none of the 16px drafts is outstanding in that regard 🤔

**Comment by tvdijen** [comment]
It`s actually a licensed image, so for a couple of bucks we could actually legaly plagiarize it 😉

**Comment by khlr** [comment]
Yep, we could simply buy it. But did you take a look at the license agreement? Maybe I get this wrong, but it says: "Not allowed: [...] Use an Item in a logo, trademark, or service mark." Unfortunately that's exactly our purpose: to use it in a logo 😕

**Comment by tvdijen** [comment]
Oh, that's too bad... I hadn't read it because I brought it up for inspiration in the first place...

**Comment by jaimeperez** [comment]
That's a pity indeed...

I'm thinking about it a little, and I believe the only ones that would be seen easily in the toolbar are 5a/b or 6a. Another option, though, would be to have two versions of the logo:

- One "inverted", with a transparent background, that could allow us to use all the space available to have a better, clearer icon for the toolbar.
- Another regular icon with the orange background, and the loupe, or key, or whatever we choose, slightly smaller to fit inside the rounded box.

Would that make sense?

**Comment by khlr** [comment]
I think the inversion is a really good idea. This has the nice side effect, that the icon seems more "baked into" the browser.

Here are some impressions:

## draft 4d:
![image](https://user-images.githubusercontent.com/17160647/37111260-864e0896-223f-11e8-8c62-9f6b83a484cb.png)

## draft 5b:
![image](https://user-images.githubusercontent.com/17160647/37111216-6efebb18-223f-11e8-98a7-357be93995ab.png)

## draft 5c:
![image](https://user-images.githubusercontent.com/17160647/37111169-51b20c40-223f-11e8-9f25-8dd1f425d61b.png)

## draft 6a:
![image](https://user-images.githubusercontent.com/17160647/37111290-967f134a-223f-11e8-823d-78568ebcd32c.png)

**Comment by khlr** [comment]
I think 5b is really clear und bold. Unfortunately it looks like a search tool. I probably wouldn't expect SAML-tracer behind that icon ;-)

6a might be ok... But I still think it's not too easy to recognize the key symbol...

5c is better, I think. But unfortunately it's quite light.
4d might be ok as well.

**Comment by tvdijen** [comment]
5b : definitely not suitable for anything other than a search-button...
5c : just doesn't do it for me
6a : a key has no connection to SAML for me

I'd go with 4d if I'd had to pick one of these

**Comment by jaimeperez** [comment]
Would [any](https://marketplace-cdn.atlassian.com/files/images/com.resolution.atlasplugins.samlsso.Confluence/3b815737-99e6-4d86-8eb0-e39d6fc091a2.png) [of](https://2.bp.blogspot.com/-jsPlIka_b_o/WYsLmoYpKvI/AAAAAAAAUbI/SgsW-oIBnqUe04CQXeHILe_I1z2DzuCagCLcBGAs/s1600/saml.jpg) [these](https://www.portalguard.com/images/icons/code.png) concepts make sense?

**Comment by khlr** [comment]
Well, I think I wouldn't associate a puzzle piece with SAML. The padlock is equally seems appropriate/inappropriate as the key symbol. And I think both are problematic in 16px.

The code-icon will certainly look good in 16px, but it's absolutely not unique. 😉 And to me it would more apply something related to coding.

It's not easy 🤔😉

The concept of a "token" is something veeery abstract. This makes it awfully hard to create a visual association for it. 
So if this term doesn't come into consideration, then we should maybe focus on the second term: the "trace"?

That's the reason I quite like draft 4d, although there may be optimizations needed. The depicted "S" is fairly crooked. I could try make this look "better". Or could the crooked look be something like a unique characteristic?

**Comment by tvdijen** [comment]
My girl is willing to try and replicate the licensed icon without plagiarizing it, if we still like that one?

**Comment by khlr** [comment]
It's probably a good idea to ask a more creative person, anyways 😊

**Comment by tvdijen** [comment]
The girlfriend came up with the following:
![img-20180310-wa0005](https://user-images.githubusercontent.com/841045/37244443-63083892-2489-11e8-806d-223bff399f8d.jpg)

**Comment by khlr** [comment]
Nice, this looks very promising 👍 

The angle brackets inside the loupe are a very good idea, I think!
Could she alter draft 1 or 2 to have a "usual" grasp instead of the connected dots (as in drafts 3-5)?

And I'd be very interested in 16px representations 😉

**Comment by tvdijen** [comment]
Are those toolbar icons really 16x16? They look more like 24x24 to me
Anyway, the grasp shouldn't be a problem if we decide to go with 1 or 2...

**Comment by khlr** [comment]
Yep, unfortunately they're 16px...

**Comment by tvdijen** [comment]
![img-20180310-wa0007](https://user-images.githubusercontent.com/841045/37245515-7a9011b4-2499-11e8-9aed-2b61546b02b2.jpg)

**Comment by tvdijen** [comment]
![img-20180310-wa0012](https://user-images.githubusercontent.com/841045/37245724-cf55cb28-249c-11e8-8c95-9f9010ba03b3.jpg)

**Comment by khlr** [comment]
They're all really easily recognizable! 👍

Well I guess then it's only a matter of personal preference. So if I had to choose, I'd pick no. 2. My second choice would be no. 3.

**Comment by jaimeperez** [comment]
They look wonderful!

I think I'd go for no. 4 or 2 from the last screenshot, though we should check how they actually look like in a real browser...

**Comment by khlr** [comment]
Do you have the possibility to clone the repo? Then you could simply modify the browser action entry in the manifest.json. 
There you'd have to provide your new icon as 16px PNG.

**Comment by tvdijen** [comment]
I can try.. But wouldn't I need a developer version of Firefox for that?
Anyway, I've asked for 16x16px PNG-exports.. Probably tomorrow night

**Comment by khlr** [comment]
That's not necessary. You can debug extensions with any version of Firefox 😊 Please, take a look at the SAML-tracer readme. The relevant resources are linked there.

If you don't have the time right now, I can assist you with that or create the pull request for you. 👍

**Comment by jaimeperez** [comment]
@tvdijen did you test the different icons?

**Comment by tvdijen** [comment]
Unfortunately, I can't get Adobe Illustrator installed on my PC :(  Perhaps anyone else that has it and can make an 16x16 export?
[no4.zip](https://github.com/UNINETT/SAML-tracer/files/2088034/no4.zip)
