### ISSUE TITLE
Not working in Firefox 60.0

### ISSUE THREAD

**Issue by philgp** [UNINETT/SAML-tracer#48]
Was working in last 59.x release. Updated to Firefox 60.0 yesterday, and now opening the SAML tracer window does open an appropriately-sized window, but it's empty.
![saml tracer screen shot 2018-05-10 at 11 51 44 am](https://user-images.githubusercontent.com/14933187/39879346-94e0a252-5448-11e8-81b5-43c258ef3eab.png)

**Comment by thijskh** [comment]
Right-click the window and content will appear. This is a known bug in Firefox.

**Comment by DanPM** [comment]
For me is not working in any firefox >5.0. Any tips?

**Comment by kevinfoote** [comment]
@thijskh, right-click worked here as well. Wshew ;) I was starting to panic and prepare to go backwards in FF versions.

**Comment by JE8** [comment]
I'm having same issue. right-click (opposite click in my case) is not working...
52.8.0 (64-bit) running on Windows 10 Enterprise.

Anyone have a perm fix? or another idea for fix?

**Comment by thijskh** [comment]
The issue is gone for me with FF 63.
