### ISSUE TITLE
Feature Request - Allow Export and Import of trace

### ISSUE THREAD

**Issue by pgmvdm** [UNINETT/SAML-tracer#5]
First of all thanks for sharing this really useful tool!

I would like to suggest a new feature that would help us a lot. For support purposes it would be great if the trace of a session could be exported to disk so that it can be imported at a later time for examination. This will allow traces to be captured and then sent (e.g. by encrypted mail) to a support organisation to diagnose a problem.

**Comment by davidbateforgerock** [comment]
Can we get an export to text feature?  Makes it easier for searching.

**Comment by thijskh** [comment]
The export is to JSON, which is a plain text format. So that makes it very well searchable, no?

**Comment by thijskh** [comment]
This can be closed.
