### ISSUE TITLE
Firefox just started disabling this add on

### ISSUE THREAD

**Issue by dgersh** [Uninett/SAML-tracer#55]
Firefox seems to have just started disabling this add on, perhaps due to a signing issue. Might be a simple fix? 

![saml-tracer](https://user-images.githubusercontent.com/1133790/57223722-0ab71a80-6fd5-11e9-93d7-33e0b0567975.png)

**Comment by tvdijen** [comment]
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Please update Firefox to the latest version to fix this issue.

**Comment by dgersh** [comment]
Excellent that did it. Usually FF notifies me of an update but I had to go chase it.

**Comment by tvdijen** [comment]
@jaimeperez Could you please close this one?

**Comment by jaimeperez** [comment]
Done!
