### ISSUE TITLE
Wrong display/export of UTF-8 strings

### ISSUE THREAD

**Issue by durkovic** [Uninett/SAML-tracer#56]
SAML tracer does not correctly display and/or export UTF-8 strings:
```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response 
....
 <saml2:Attribute FriendlyName="displayName"
                  Name="urn:oid:2.16.840.1.113730.3.1.241"
                  NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                  > 
      <saml2:AttributeValue>Marian ÄurkoviÄ</saml2:AttributeValue>
 </saml2:Attribute>
```

Same problem in exported .json file

**Comment by khlr** [comment]
Thank you for reporting this issue and sorry for the late reply.
I think PR #57 should do the trick :-)

**Comment by durkovic** [comment]
Thanks, with your patch accented chars are displayed correctly.

**Comment by jaimeperez** [comment]
Thanks @durkovic for reporting this and @khlr for fixing it! I've just merged the PR 😄
