### ISSUE TITLE
Enable/disable tracing without closing window

### ISSUE THREAD

**Issue by CBongo** [UNINETT/SAML-tracer#8]
Feature request:

LiveHeaders has a  checkbox control to enable/disable the tracing function itself while leaving its window open.  This is useful if you are trying to debug an issue while your browser continues auto-refreshing unrelated pages in the background.

Something like this would be handy in SAML-tracer.  It could be added as a button alongside the "Clear", "Autoscroll", and "Filter resources" buttons at the top of the window.

**Comment by jaimeperez** [comment]
Available in SAML tracer 1.3.
